# Generated by Django 5.0 on 2023-12-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrresult',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='ocrresult',
            name='success',
        ),
    ]
