# Generated by Django 5.0 on 2023-12-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_ocrresult_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='date_of_expiry',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='date_of_issue',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='identification_number',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
